### ISSUE TITLE
Add possibility to use pip requirements file as input

### ISSUE THREAD

**Issue by Danzelot** [DeiC-HPC/cotainr#101]
It would ease transition to cotainr for many users if they can also use pip requirements file. So, that they don't have to transcribe their requirements file to conda yml before using cotainr.

**Comment by Chroxvi** [comment]
You should be able to [reference the pip `requirements.txt`](https://pip.pypa.io/en/stable/reference/requirements-file-format/#referring-to-other-requirements-files) in the `conda_env.yml` file, e.g. something along the lines of:

```yaml
name: my_conda_env
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.11
  - pip:
    - -r /tmp/requirements.txt
```

should work as a generic starting point if you already have a `requirements.txt`. Note that the `requirements.txt` file must be placed in some location that is accessible from within the container, e.g. `/tmp`.
