### ISSUE TITLE
Improve documentation: private github repositories and ssh-agent forwarding

### ISSUE THREAD

**Issue by cscjlan** [DeiC-HPC/cotainr#53]
It seems as though it's possible to use private github repositories with `pip` in the conda environment file only if one uses ssh-agent forwarding. This is because apptainer can use keys from the [host ssh-agent](https://stackoverflow.com/questions/65252415/use-ssh-key-of-host-during-singularity-apptainer-build) but not from the host filesystem.

It would be useful to mention this in the documentation, even though it's not related to cotainr per se, but rather to apptainer.

An example conda environment file, where the `foo/bar.git` is a private repository. This only works, if the host machine uses ssh-agent forwarding.
```yaml
name:
  - test_cotainr
channels:
  - conda-forge
dependencies:
  - python=3.11
  - git
  - openssh
  - pip
  - pip:
    - "--editable=git+ssh://git@github.com/foo/bar.git@SOMEHASHCODE#egg=baz"
```

This was tested on LUMI with `cotainr/2023.01.0-cray-python-3.9.12.1`
